//
// Created by prodigg on 22.02.26.
//

#ifndef CPPADSPROMETEUSCONNECTOR_PROMETHEUSENDPOINT_H
#define CPPADSPROMETEUSCONNECTOR_PROMETHEUSENDPOINT_H

#include <thread>
#include <vector>

#include "ProcessDataBuffer.h"
#include "AdsVariableList.h"
#include <pistache/endpoint.h>
#include <pistache/router.h>
#include "nlohmann/json.hpp"
using json = nlohmann::json;

/*
 * Prometheus formate:
 *
 * #HELP <metric_name> <description>
 * #TYPE <metric_name> <[counter], [gauge], [untyped]>
 * <metric_name> <data> <timestamp>
 */

enum class prometheusMetricType {
    UNTYPED = 0,
    COUNTER,
    GAUGE
};

struct label_t {
    std::string label;
    std::string value;
};

struct additionalDataMetric_t {
    bool show = false; // if true, show the metric
    bool carryLabels = true; // if true, use labels from symbol
    std::string alias; // if true use another name, than the autogenerated one (e.g. symbolName_<additionalDataName>)
    std::string customDescription; // if empty use default one
    std::vector<label_t> labels;
};

struct prometheusMetric_t {
    prometheusMetricType metricType; // Type of metric
    const std::string symbolName; // symbol name in the process buffer
    std::string_view description; // optional description if empty omit description
    std::string_view alias; // choose other name for symbol name in the endpoint if empty, use symbol name
    std::vector<label_t> labels; // array of optional labels

    additionalDataMetric_t currentLastTime; // a metric for time between last and current read
    additionalDataMetric_t ReadTime; // time to read a symbol
    additionalDataMetric_t LastTryStatus; // status of last try
    additionalDataMetric_t LastReadTimestamp; // the timestamp of the last read
};

class grafanaMetricGenerator_t;

class PrometheusEndpoint_t {
public:
    explicit PrometheusEndpoint_t(ProcessDataBuffer_t& dataBuffer, uint16_t port);

    /*!
     * @brief adds a symbol to the endpoint
     * @param metric data for the metric to add
     * @return successful
     */
    bool addSymbol(const prometheusMetric_t& metric);

    /*!
     * @brief this method starts the endpoint
     */
    void serve() {
        endpoint.serve();
    }
private:

    /*!
     * @brief this is the main thread function
     */
    void threadLoop(std::stop_token stoken);

    /*!
     * @brief this is the callback to retrieve data
     */
    void getData(const Pistache::Rest::Request& request, Pistache::Http::ResponseWriter response) const;

    /*!
     * @brief get the prometheus metric name
     * @param metric
     * @return
     */
    static std::string getPrometheusMetricName(const prometheusMetric_t& metric);

    /*!
     * @brief generates the full endpoint data to serve
     * @return
     */
    std::string generateEndpointData() const;

    /*!
     * @brief generate prometheus symbol for additional data
     * @param data additional data
     * @return
     */
    std::string generateAdditionalData(const prometheusMetric_t& metric, const additionalDataMetric_t& data, const std::string&& normalNamePrefix, const std::string&& normalDescription, const std::string& value) const;


    /*!
     * @brief this is the callback for the root page, it provides a nice welcome text for the user
     */
    void getRootPageData(const Pistache::Rest::Request& request, Pistache::Http::ResponseWriter response);

    /*!
     * @brief this is the callback for the additional information page, it provides additional data in a json formate
     */
    void getAdditionalInformationPageData(const Pistache::Rest::Request& request, Pistache::Http::ResponseWriter response);

    std::string generateAdditionalInformation();

    std::vector<prometheusMetric_t> _metrics;
    std::optional<std::jthread> _thread;
    ProcessDataBuffer_t& _dataBuffer;

    Pistache::Http::Endpoint::Options opts = Pistache::Http::Endpoint::options().threads(1);
    Pistache::Address addr;
    Pistache::Http::Endpoint endpoint;
    Pistache::Rest::Router router;
};

class grafanaMetricGenerator_t {
public:
    /*!
     * @brief generate a metric string
     * @param metricName
     * @param data
     * @param helpStr
     * @param type
     * @param labels
     * @param readTime
     * @return metric string
     */
    [[nodiscard]] static std::string generateMetric(
        std::string_view metricName,
        std::string_view data,
        std::string_view helpStr,
        prometheusMetricType type,
        const std::vector<label_t>& labels,
        std::chrono::system_clock::time_point readTime);


private:
    /*!
     * @brief properly escape the label text
     * @param str
     * @return
     */
    [[nodiscard]] static std::string escapeLabelStr(std::string_view str);

    /*!
     * @brief properly escape the help text
     * @param str
     * @return
     */
    [[nodiscard]] static std::string escapeHelpStr(std::string_view str);

    /*!
     * @brief generate the help text for the prometheus endpoint
     * @param helpStr
     * @param metricName
     * @return
     */
    [[nodiscard]] static std::string generateHelp(std::string_view helpStr, std::string_view metricName);

    /*!
     * @brief generate the type text for the prometheus endpoint
     * @param type
     * @param metricName
     * @return
     */
    [[nodiscard]] static std::string generateType(prometheusMetricType type, std::string_view metricName);

    /*!
     * @brief generate the dataline for the prometheus endpoint
     * @param metricName
     * @param data
     * @param labels
     * @param dataReadTime
     * @return
     */
    [[nodiscard]] static std::string generateDataLine(std::string_view metricName, std::string_view data, const std::vector<label_t>& labels, std::chrono::system_clock::time_point dataReadTime);

    /*!
     * @brief generates the label string for additional categorization.
     * @param labels
     * @return
     */
    [[nodiscard]] static std::string generateLabel(const std::vector<label_t>& labels);
};

#endif //CPPADSPROMETEUSCONNECTOR_PROMETHEUSENDPOINT_H