//
// Created by prodigg on 08.04.26.
//

#ifndef ADSPROMETHEUSCONNECTOR_PROMETHEUSBUILDER_H
#define ADSPROMETHEUSCONNECTOR_PROMETHEUSBUILDER_H
#include <thread>
#include <vector>
#include <string>
#include <string_view>
#include <sstream>

/*
 * Prometheus formate:
 *
 * #HELP <metric_name> <description>
 * #TYPE <metric_name> <[counter], [gauge], [untyped]>
 * <metric_name> <data> <timestamp>
 */

enum class prometheusMetricType {
    UNTYPED = 0,
    COUNTER,
    GAUGE
};

struct label_t {
    std::string label;
    std::string value;
};

struct additionalDataMetric_t {
    bool show = false; // if true, show the metric
    bool carryLabels = true; // if true, use labels from symbol
    std::string alias; // if true use another name, than the autogenerated one (e.g. symbolName_<additionalDataName>)
    std::string customDescription; // if empty use default one
    std::vector<label_t> labels;
};

struct prometheusMetric_t {
    prometheusMetricType metricType; // Type of metric
    const std::string symbolName; // symbol name in the process buffer
    std::string_view description; // optional description if empty omit description
    std::string_view alias; // choose other name for symbol name in the endpoint if empty, use symbol name
    std::vector<label_t> labels; // array of optional labels

    additionalDataMetric_t currentLastTime; // a metric for time between last and current read
    additionalDataMetric_t ReadTime; // time to read a symbol
    additionalDataMetric_t LastTryStatus; // status of last try
    additionalDataMetric_t LastReadTimestamp; // the timestamp of the last read
};


class grafanaMetricGenerator_t {
public:
    /*!
     * @brief generate a metric string
     * @param metricName
     * @param data
     * @param helpStr
     * @param type
     * @param labels
     * @param readTime
     * @return metric string
     */
    [[nodiscard]] static std::string generateMetric(
        std::string_view metricName,
        std::string_view data,
        std::string_view helpStr,
        prometheusMetricType type,
        const std::vector<label_t>& labels,
        std::chrono::system_clock::time_point readTime);


private:
    /*!
     * @brief properly escape the label text
     * @param str
     * @return
     */
    [[nodiscard]] static std::string escapeLabelStr(std::string_view str);

    /*!
     * @brief properly escape the help text
     * @param str
     * @return
     */
    [[nodiscard]] static std::string escapeHelpStr(std::string_view str);

    /*!
     * @brief generate the help text for the prometheus endpoint
     * @param helpStr
     * @param metricName
     * @return
     */
    [[nodiscard]] static std::string generateHelp(std::string_view helpStr, std::string_view metricName);

    /*!
     * @brief generate the type text for the prometheus endpoint
     * @param type
     * @param metricName
     * @return
     */
    [[nodiscard]] static std::string generateType(prometheusMetricType type, std::string_view metricName);

    /*!
     * @brief generate the dataline for the prometheus endpoint
     * @param metricName
     * @param data
     * @param labels
     * @param dataReadTime
     * @return
     */
    [[nodiscard]] static std::string generateDataLine(std::string_view metricName, std::string_view data, const std::vector<label_t>& labels, std::chrono::system_clock::time_point dataReadTime);

    /*!
     * @brief generates the label string for additional categorization.
     * @param labels
     * @return
     */
    [[nodiscard]] static std::string generateLabel(const std::vector<label_t>& labels);
};

#endif //ADSPROMETHEUSCONNECTOR_PROMETHEUSBUILDER_H